Boddlnagg/midir

examples/test.rs, examples/test_play.rs, examples/test_reuse.rs, examples/test_sysex.rs, examples/test_virtual.rs, src/backend/alsa/mod.rs, src/backend/coremidi/mod.rs, src/errors.rs
Implement the `Error` trait correctly for `ConnectError`, as it should have been done from the beginning (but wasn't possible for some reason).
This is a breaking change, because `ConnectErrorKind` does not impl `Error` any more!
Also change all occurences of `try!` to use `?` instead, which makes the examples a bit nicer.
=> impl Error for ConnectError (the right way)

Cargo.toml, src/backend/winmm/handler.rs, src/backend/winmm/mod.rs
DO NOT MERGE YET
This is only a test, because winapi 0.3 has not yet been released (it's specified as a git dependency). See retep998/winapi-rs#316.
=> Update to winapi 0.3

Cargo.toml, README.md, appveyor.yml, src/backend/mod.rs, src/backend/winrt/mod.rs
Fixes #24.
Interestingly, playing around with the `test_forward` example, I found that the WinMM backend is slower than the WinRT backend when I just forward from a MIDI controller to the built-in `Microsoft GS Wavetable Synth`. With WinMM there's a noticable delay, but with the new WinRT backend it's actually real-time!
~~This PR depends on (i.e. includes) #26. Hence, #26 should be merged before this.~~
~~Currently a git version of the `winrt` crate is used. PR should not be merged until a new version has been released.~~
=> WinRT backend

examples/test_read_input.rs
Thanks for your work on this crate. I wanted to use midir solely as a receiver of midi events, so this PR adds an example which doesn't require a midi output. 
It is very similar to some of the other examples, but I couldn't get the others to run because I don't have a midi output device to send to, I only have a midi input device.
=> add read input example

Cargo.toml, examples/test_forward.rs, examples/test_list_ports.rs, examples/test_play.rs, examples/test_read_input.rs, examples/test_reuse.rs, examples/test_sysex.rs, src/backend/alsa/mod.rs, src/backend/coremidi/mod.rs, src/backend/jack/mod.rs, src/backend/jack/wrappers.rs, src/backend/winmm/handler.rs, src/backend/winmm/mod.rs, src/backend/winrt/mod.rs, src/common.rs, src/errors.rs, tests/virtual.rs
Implements #32.
This is not ready yet ... still missing:
=> Per-platform unique port identifiers

Cargo.toml, README.md, examples/browser/Cargo.toml, examples/browser/index.html, examples/browser/src/lib.rs, examples/test_forward.rs, examples/test_sysex.rs, src/backend/mod.rs, src/backend/webmidi/mod.rs, src/common.rs, tests/virtual.rs
Web MIDI is all kinds of asyncronous.  Devices won't be available if you try to block request them immediately.  It's possible that sending a MIDI device input immediately after opening it, if that input device requires system exclusive access, may not work.  It'd perhaps be possible to buffer data until the promise for opening the device resolves...
```cmd
C:\local\midir\examples\browser> wasm-pack build --target=no-modules --dev
...
C:\local\midir\examples\browser> "%ProgramFiles(x86)%\Google\Chrome\Application\chrome.exe" --allow-file-access-from-files --auto-open-devtools-for-tabs file:///C:\local\midir\examples\browser\index.html
```
Note that existing chrome instances may interfere with using command line flags - you may prefer to use the …
=> Web MIDI support.

examples/test_forward.rs, examples/test_list_ports.rs, examples/test_play.rs, examples/test_read_input.rs, examples/test_reuse.rs, examples/test_sysex.rs, src/backend/alsa/mod.rs, src/backend/coremidi/mod.rs, src/backend/jack/mod.rs, src/backend/jack/wrappers.rs, src/backend/winmm/mod.rs, src/backend/winrt/mod.rs, src/errors.rs
Hi. Really nice library! I want to get in to coding my MIDI things using Rust.
However, when building the examples I noticed a number of warnings. Many of them deprecation warnings. But they are easily fixed. So I thought I'd brush it up a little bit.
* `Error::description` has been soft deprecated since Rust 1.27 and was hard deprecated in 1.42. So I remove those implementations and let users rely on the `Display` impl of errors. Should maybe be considered a breaking change in a way. The exposed API is identical, but user's will get nonsense messages if they still call `.description()` after this lands.
* Trait objects without the `dyn` keyword are deprecated. So I just added the `dyn` keyword.
* Constants default to the static lifetime. There is no other lifetime they can have. So the …
=> Modernize / fix warnings

Cargo.toml, src/backend/jack/mod.rs, src/backend/jack/wrappers.rs
Bitflags 0.3 is from 2015 and a lot happened since then.
There were a few macro syntax differences and the constants became associated constants so they had to be accessed a bit differently, but otherwise not much of the code had to be changed.
This version of `bitflags` uses `?` internally for error handling instead of the deprecated `try!` so compiling causes a lot fewer warnings now.
=> Upgrade bitflags

src/backend/jack/mod.rs, src/backend/jack/wrappers.rs, src/backend/winmm/mod.rs
Hi! 
`std::mem::uninitialized` was [deprecated in Rust 1.39.0](https://doc.rust-lang.org/std/mem/fn.uninitialized.html), and the recommended pattern is to replace it with `std::mem::MaybeUninit`.  This is a little PR to migrate in case downstream crates forbid the use of deprecated calls (my use case)
* Replaces calls to uninitialized() with MaybeUninit where appropriate
* Replace uninitialized memory in SysexBuffer with array of null pointers instead, which can be checked in the case of failure.
=> Remove usage of mem::uninitialized

Cargo.toml, src/backend/winrt/mod.rs
Update to the latest version of the "winrt" crate, which is now maintained by Microsoft (https://github.com/microsoft/winrt-rs).
=> Use winrt-rs instead of winrt-rust

examples/browser/Cargo.toml, examples/browser/src/lib.rs
This resolves a TODO in the WebMIDI example in the browser to prompt the user if there are multiple in ports. This just does a simple loop prompting the user until valid port number is entered.
I'm pretty new to both Rust and MIDI, so please let me know if I did anything wrong!
=> WebMIDI Example: Prompt user if multiple inputs are available

Cargo.toml, src/backend/alsa/mod.rs
Fixes #62 (Update alsa dependency to 0.4.2)
In order to update _alsa_, I had also to update _nix_ to avoid further compile errors.
=> Update dependencies (alsa to 0.4.2, nix to 0.15)

src/common.rs
Looks like there was a copy paste error
=> Correct a typo in a docstring

src/backend/alsa/mod.rs, src/backend/coremidi/mod.rs, src/backend/jack/mod.rs, src/backend/webmidi/mod.rs, src/backend/winmm/mod.rs, src/backend/winrt/mod.rs, src/common.rs
It would be useful if we could compare ports directly by their identificator.
=> Implement PartialEq For Midi Ports

Cargo.toml, src/backend/alsa/mod.rs
Since nix that is dependency crate is old, midir cannot build for riscv64gc.
riscv64gc support is added by nix 0.18. So I would like to update alsa to 0.5.0
=> Update alsa to 0.6.0 to support riscv64 target

Cargo.toml, src/backend/mod.rs
Allows `coremidi` back-end to be compiled for iOS targets.
Note: I haven't done any testing that this will work on iOS devices
=> Fix ios compilation

src/backend/alsa/mod.rs
Previously, the ALSA backend created a new `Vec<pollfd>`, then immediately called `Vec::set_len`. This exposes uninitialized `pollfd`s, which causes undefined behaviour. This commit fixes this by initializing the `Vec` with invalid, but still initialized, `pollfd`s before filling it. In addition, this commit simplifies the code slightly by removing the usage of `Vec::into_boxed_slice`.
Fixes #110.
=> Fix undefined behaviour in the ALSA backend

Cargo.toml, src/backend/winmm/mod.rs, src/lib.rs
`PSTR` has moved to `core`, that's it.
Yes, the windows crate is [churning a bit much](https://github.com/microsoft/windows-rs/issues/1720), work is underway to make that better but for now, it's a quickly moving upgrade train...
=> Update windows crate to 0.37, remove memalloc dependency

src/backend/alsa/mod.rs
Searching for either WRITE or SUB_WRITE capabilities causes filling of the ports list with a bunch of ports that are impossible to connect to and always return an error if you try to. I believe that the correct way is to search for both.
Alsa utils do the same:
Search for readable:
https://github.com/alsa-project/alsa-utils/blob/a566f8a0ed6d7ca5fd6ae2d224f3f28654a2f3be/seq/aplaymidi/arecordmidi.c#L685-L689
Search for writable:
https://github.com/alsa-project/alsa-utils/blob/a566f8a0ed6d7ca5fd6ae2d224f3f28654a2f3be/seq/aplaymidi/aplaymidi.c#L832-L836
=> [alsa] Fix port listing

src/backend/alsa/mod.rs
ALSA has a default buffer of 16k (on my machine), and sending MIDI messages larger than this requires a call to
snd_seq_set_output_buffer_size(), which is unfortunately not exposed by the alsa crate, first.
Therefore, use event_output_direct instead, which allocates a temporary buffer[1].
1: https://www.alsa-project.org/alsa-doc/alsa-lib/group___seq_event.html#ga63986686b918abeff9902108638c5b2f
=> Send MIDI messages on ALSA directly

Cargo.toml, azure-pipelines-template.yml, azure-pipelines.yml, src/backend/jack/wrappers.rs
This PR resolves build issues with the `jack` feature enabled and bumps the `jack-sys` version to the latest one. Tested on Arch Linux and Ubuntu 22.04.
=> Fix Jack build on ARM and bump jack-sys version

Cargo.toml
The changes in `coremidi` 0.8.0 since the previous 0.6.0 don't affect the API used by `midir`.
You can see the changelog here: https://github.com/chris-zen/coremidi/releases
=> Update coremidi to 0.8.0

Cargo.toml, src/backend/alsa/mod.rs
The `alsa::nix::errno::Errno` -> `libc` changes are since alsa 0.9 stopped using nix: https://github.com/diwic/alsa-rs/pull/116
=> Update alsa from 0.7 to 0.9

Cargo.toml, src/backend/winmm/handler.rs, src/backend/winmm/mod.rs, src/backend/winrt/mod.rs
* Mutexes in Windows are re-entrant, but `std::sync::Mutex` is not.
* If a sysex message is inbound when closing a MIDI input windows will hang because part of the call to `midiInReset` will cause the input handler to fire, but the `HMIDIIN` lock was already taken before that handler attempts to take the lock a second time.
* All of this takes place in a single thread, so there's no risk in allowing the lock to be taken twice.
* `parking_lot::ReentrantMutex` is used in place of `Mutex`.
* This change should behave more like `rtmidi` (which some of this code is based on) as `rtmidi` is also using a re-entrant mutex.
* Tested on Windows 10, and issue appears resolved.
Fixes #150
=> fix: Windows hangs when closing midi input

src/backend/alsa/mod.rs, src/backend/coremidi/mod.rs, src/backend/jack/mod.rs, src/backend/webmidi/mod.rs, src/backend/winmm/mod.rs, src/backend/winrt/mod.rs, src/common.rs
Allows getting a unique reference to the port as an opaque string. The main advantage of this over just using the `MidiInputPort` and `MidiOutputPort` structs is that this identifier can be serialized.
In my case i'm trying to make [`tauri-plugin-midi`](https://github.com/specta-rs/tauri-plugin-midi) work with many different devices that have the same device name. Being able to serialize these identifiers means we can share them with the webview and use them to address any communications.
By using the identifiers from the OS midi stuff, we should also be able to get identifier which are stable across restarts of the application (and potentially the system but that's *really up to the OS*).
I think this might close #34
One implication of the code in this PR is that it does some lossy …
=> Add `MidiInputPort::id()` and `MidiOutputPort::id()`

src/backend/coremidi/mod.rs
Closes #132 
This is an attempt to fix an issue where it's not possible to upload to the App Store using this library on iOS, as it uses the private CoreAudio APIs `AudioGetCurrentHostTime` and `AudioConvertHostTimeToNanos`.
This PR simply removes skips the timestamp on iOS, rather than using a feature.
=> Disable use of private CoreAudio APIs for timestamping on iOS
